// <auto-generated/>
// Zomp.MethodCloning, compiled into the generator which references the package. Marked as
// generated so that the analyzers of that generator leave it alone.
#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;

namespace Zomp.MethodCloning;

/// <summary>
/// A method rewritten by a transformation, ready to be emitted into a file of its own.
/// </summary>
/// <param name="Location">Where the original method sits.</param>
/// <param name="FileName">Stem of the name of the file the method is emitted to, by default the name of the original method.</param>
/// <param name="Implementation">The rewritten method.</param>
/// <param name="NullableDisabled">True to leave the <c>#nullable enable</c> directive out of the file.</param>
/// <param name="Diagnostics">Diagnostics the transformation reported.</param>
/// <param name="HasErrors">True if there are errors in <see cref="Diagnostics"/>, in which case nothing is emitted.</param>
/// <param name="Signature">Signature the rewritten method will be emitted with, used to detect colliding overloads.</param>
internal sealed record ClonedMethod(
    MethodLocation Location,
    string FileName,
    string Implementation,
    bool NullableDisabled,
    EquatableArray<ReportedDiagnostic> Diagnostics,
    bool HasErrors,
    MethodSignature? Signature)
{
    /// <summary>
    /// Creates a cloned method from the result of rewriting it.
    /// </summary>
    /// <param name="location">Where the original method sits.</param>
    /// <param name="original">Declaration of the original method.</param>
    /// <param name="rewritten">Result of rewriting the method, or the extension block which holds it.</param>
    /// <param name="nullableDisabled">True to leave the <c>#nullable enable</c> directive out of the file.</param>
    /// <param name="diagnostics">Diagnostics the transformation reported.</param>
    /// <param name="fileName">
    /// Stem of the name of the file the method is emitted to. A transformation which clones a
    /// method more than once gives each copy its own, since files named after the same method
    /// would collide. Defaults to the name of the original method.
    /// </param>
    /// <returns>A new <see cref="ClonedMethod"/>.</returns>
    public static ClonedMethod Create(
        MethodLocation location,
        MethodDeclarationSyntax original,
        SyntaxNode rewritten,
        bool nullableDisabled,
        ImmutableArray<ReportedDiagnostic> diagnostics,
        string? fileName = null)
    {
        var hasErrors = false;
        foreach (var diagnostic in diagnostics)
        {
            hasErrors |= diagnostic.Descriptor.DefaultSeverity == DiagnosticSeverity.Error;
        }

        return new(
            location,
            fileName ?? original.Identifier.ValueText,
            rewritten.ToFullString(),
            nullableDisabled,
            diagnostics,
            hasErrors,
            MethodSignature.Create(rewritten, location, original));
    }
}
