// <auto-generated/>
// Zomp.MethodCloning, compiled into the generator which references the package. Marked as
// generated so that the analyzers of that generator leave it alone.
#nullable enable

namespace Zomp.MethodCloning;

/// <summary>
/// The kind of a type a method is nested in.
/// </summary>
internal enum ContainingTypeKind
{
    Class,
    Struct,
    Record,
    Interface,
}
