// <auto-generated/>
// Zomp.MethodCloning, compiled into the generator which references the package. Marked as
// generated so that the analyzers of that generator leave it alone.
#nullable enable

namespace Zomp.MethodCloning;

internal enum MethodParent
{
    Class,
    Struct,
    Record,
    Interface,
}
