// <auto-generated/>
// Zomp.MethodCloning, compiled into the generator which references the package. Marked as
// generated so that the analyzers of that generator leave it alone.
#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;

namespace Zomp.MethodCloning;

/// <summary>
/// A diagnostic in a form the incremental pipeline can compare and cache. A
/// <see cref="Diagnostic"/> holds a <see cref="Location"/>, which keeps the syntax tree alive and
/// compares by reference.
/// </summary>
/// <param name="Descriptor">Descriptor of the diagnostic.</param>
/// <param name="FilePath">Path of the file the diagnostic is reported in.</param>
/// <param name="TextSpan">Span the diagnostic is reported at.</param>
/// <param name="LineSpan">Lines the diagnostic is reported at.</param>
/// <param name="MessageArguments">Arguments of the descriptor's message format.</param>
/// <see href="https://github.com/dotnet/roslyn/issues/62269#issuecomment-1170760367" />
internal sealed record ReportedDiagnostic(DiagnosticDescriptor Descriptor, string FilePath, TextSpan TextSpan, LinePositionSpan LineSpan, EquatableArray<string> MessageArguments)
{
    /// <summary>
    /// Implicitly converts <see cref="ReportedDiagnostic"/> to <see cref="Diagnostic"/>.
    /// </summary>
    /// <param name="diagnostic">Diagnostic to convert.</param>
    public static implicit operator Diagnostic(ReportedDiagnostic diagnostic)
        => Diagnostic.Create(
            descriptor: diagnostic.Descriptor,
            location: Location.Create(diagnostic.FilePath, diagnostic.TextSpan, diagnostic.LineSpan),
            messageArgs: [.. diagnostic.MessageArguments]);

    /// <summary>
    /// Creates a new <see cref="ReportedDiagnostic"/> from <see cref="DiagnosticDescriptor"/> and <see cref="Location"/>.
    /// </summary>
    /// <param name="descriptor">Descriptor of the diagnostic.</param>
    /// <param name="location">Where the diagnostic is reported.</param>
    /// <param name="messageArguments">Arguments of the descriptor's message format.</param>
    /// <returns>A new <see cref="ReportedDiagnostic"/>.</returns>
    public static ReportedDiagnostic Create(DiagnosticDescriptor descriptor, Location location, params string[] messageArguments)
        => new(descriptor, location.SourceTree?.FilePath ?? string.Empty, location.SourceSpan, location.GetLineSpan().Span, ImmutableArray.Create(messageArguments));
}
