<Project Sdk="Microsoft.NET.Sdk">

  <!-- Uses the Variants generator from its package. -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Zomp.MethodCloning.Variants" PrivateAssets="all" />
  </ItemGroup>

</Project>
