namespace Zomp.MethodCloning.Variants;

/// <summary>
/// Writes the variants of each method <c>[CloneVariants]</c> marks, from the one written by hand.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class VariantGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Metadata name of the attribute which marks the methods to write variants of.
    /// </summary>
    internal const string AttributeName = "Zomp.MethodCloning.CloneVariantsAttribute";

    private const string AttributeSource = """
// <auto-generated/>
namespace Zomp.MethodCloning
{
    /// <summary>
    /// Writes variants of a method from the one written by hand. The word naming the variant the
    /// method was written for is swapped for each of the others: in the name of the method, in the
    /// types and static members it refers to, and in its documentation.
    /// </summary>
    /// <remarks>
    /// Applied to a partial type, it marks every method in the same declaration of the type.
    /// </remarks>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Method |
        global::System.AttributeTargets.Class |
        global::System.AttributeTargets.Struct |
        global::System.AttributeTargets.Interface,
        AllowMultiple = false,
        Inherited = false)]
    [global::System.Diagnostics.Conditional("ZOMP_METHOD_CLONING_ATTRIBUTES")]
    internal sealed class CloneVariantsAttribute : global::System.Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CloneVariantsAttribute"/> class.
        /// </summary>
        /// <param name="original">The word naming the variant the method is written for, such as <c>Bmp</c>.</param>
        /// <param name="variants">The words naming the variants to write, such as <c>Gif</c> and <c>Png</c>.</param>
        public CloneVariantsAttribute(string original, params string[] variants)
        {
        }
    }
}
""";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource(
            "CloneVariantsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var variants = CloneTarget.ForAttribute(context.SyntaxProvider, AttributeName)
            .SelectMany(static (target, ct) => Clone(target, ct))
            .WithTrackingName("Clone");

        ClonedMethodOutput.Register(context, variants, VariantDiagnostics.CollidingVariants);

        // Roslyn 4.8, which this generator is built against, cannot declare an extension block
        // again, so a member of one is reported instead of silently left without variants.
        var extensionMembers = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeName,
            predicate: static (node, _) => node is MethodDeclarationSyntax { Parent: TypeDeclarationSyntax { Keyword.ValueText: "extension" } },
            transform: static (ctx, _) =>
            {
                var identifier = ((MethodDeclarationSyntax)ctx.TargetNode).Identifier;
                return ReportedDiagnostic.Create(VariantDiagnostics.ExtensionBlockMember, identifier.GetLocation(), identifier.ValueText);
            });

        context.RegisterSourceOutput(extensionMembers, static (spc, diagnostic) => spc.ReportDiagnostic(diagnostic));
    }

    private static ImmutableArray<ClonedMethod> Clone(CloneTarget target, CancellationToken ct)
    {
        var context = target.Context;
        var syntax = target.Syntax;
        var isTargetType = context.TargetSymbol is ITypeSymbol;

        var symbol = isTargetType
            ? context.SemanticModel.GetDeclaredSymbol(syntax, ct)
            : context.TargetSymbol as IMethodSymbol;

        if (symbol is null
            || context.Attributes[0].ConstructorArguments is not [{ Value: string original }, { Values: var variants }]
            || !MethodLocation.TryCreate(syntax, symbol, out var location, out var root))
        {
            return ImmutableArray<ClonedMethod>.Empty;
        }

        // An attribute on the method wins over the one on its type.
        if (isTargetType && symbol.GetAttributes().Any(static a => a.AttributeClass?.ToDisplayString() == AttributeName))
        {
            return ImmutableArray<ClonedMethod>.Empty;
        }

        // Each variant keeps the nullable context the method was written in, so that a method
        // written without annotations does not gain them in its variants.
        var nullableDisabled = !context.SemanticModel.GetNullableContext(syntax.SpanStart).AnnotationsEnabled();

        var name = syntax.Identifier.ValueText;

        if (name.IndexOf(original, StringComparison.Ordinal) < 0)
        {
            var diagnostic = ReportedDiagnostic.Create(VariantDiagnostics.NameWithoutOriginal, syntax.Identifier.GetLocation(), name);
            return ImmutableArray.Create(ClonedMethod.Create(location, syntax, syntax, nullableDisabled, ImmutableArray.Create(diagnostic)));
        }

        var clones = ImmutableArray.CreateBuilder<ClonedMethod>();

        foreach (var variant in variants)
        {
            if (variant.Value is not string to || string.Equals(to, original, StringComparison.Ordinal))
            {
                continue;
            }

            var rewriter = new VariantRewriter(context.SemanticModel, syntax, original, to);
            var rewritten = rewriter.Visit(root);

            var compilation = context.SemanticModel.Compilation;
            var variantLocation = location with
            {
                OuterUsings = RenameUsings(location.OuterUsings, original, to, compilation),
                InnerUsings = RenameUsings(location.InnerUsings, original, to, compilation),
            };

            // Each file is named after the method and the variant. The variant's name alone would
            // not do: methods written for different variants, such as GetBmpMetadata and an
            // overload GetGifMetadata, can both produce a GetPngMetadata.
            clones.Add(ClonedMethod.Create(variantLocation, syntax, rewritten, nullableDisabled, rewriter.Diagnostics, $"{name}.{to}"));
        }

        return clones.ToImmutable();
    }

    /// <summary>
    /// Swaps the word in the using directives of the file a variant is emitted to, so that
    /// <c>using Formats.Bmp;</c> becomes <c>using Formats.Gif;</c> and the references the
    /// documentation makes by simple name resolve. A directive is swapped only when the namespace
    /// it would name exists; aliases and static directives are kept as they are.
    /// </summary>
    /// <param name="usings">The directives of the original file.</param>
    /// <param name="original">The word naming the variant the method was written for.</param>
    /// <param name="variant">The word naming the variant to write.</param>
    /// <param name="compilation">The compilation, to look the namespaces up in.</param>
    /// <returns>The directives for the variant, without duplicates.</returns>
    private static EquatableArray<string> RenameUsings(EquatableArray<string> usings, string original, string variant, Compilation compilation)
    {
        const string prefix = "using ";

        var renamed = ImmutableArray.CreateBuilder<string>();

        foreach (var directive in usings)
        {
            var candidate = directive;

            if (directive.StartsWith(prefix, StringComparison.Ordinal)
                && !directive.StartsWith("using static ", StringComparison.Ordinal)
                && directive.EndsWith(";", StringComparison.Ordinal)
                && directive.IndexOf('=') < 0)
            {
                var name = directive.Substring(prefix.Length, directive.Length - prefix.Length - 1).Trim();
                var counterpart = VariantRewriter.Rename(name, original, variant);

                if (!string.Equals(counterpart, name, StringComparison.Ordinal) && NamespaceExists(compilation.GlobalNamespace, counterpart))
                {
                    candidate = prefix + counterpart + ";";
                }
            }

            if (!renamed.Contains(candidate))
            {
                renamed.Add(candidate);
            }
        }

        return renamed.ToImmutable();
    }

    private static bool NamespaceExists(INamespaceSymbol globalNamespace, string name)
    {
        var current = globalNamespace;

        foreach (var part in name.Split('.'))
        {
            var next = current.GetNamespaceMembers().FirstOrDefault(n => string.Equals(n.Name, part, StringComparison.Ordinal));

            if (next is null)
            {
                return false;
            }

            current = next;
        }

        return true;
    }
}
