using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Zomp.MethodCloning.Variants;

/// <summary>
/// Writes the variants of each method <c>[CloneVariants]</c> marks, from the one written by hand.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class VariantGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Metadata name of the attribute which marks the methods to write variants of.
    /// </summary>
    internal const string AttributeName = "Zomp.MethodCloning.CloneVariantsAttribute";

    private const string AttributeSource = """
// <auto-generated/>
namespace Zomp.MethodCloning
{
    /// <summary>
    /// Writes variants of a method from the one written by hand. The word naming the variant the
    /// method was written for is swapped for each of the others: in the name of the method, in the
    /// types and static members it refers to, and in its documentation.
    /// </summary>
    /// <remarks>
    /// Applied to a partial type, it marks every method in the same declaration of the type.
    /// </remarks>
    [global::System.AttributeUsage(
        global::System.AttributeTargets.Method |
        global::System.AttributeTargets.Class |
        global::System.AttributeTargets.Struct |
        global::System.AttributeTargets.Interface,
        AllowMultiple = false,
        Inherited = false)]
    [global::System.Diagnostics.Conditional("ZOMP_METHOD_CLONING_ATTRIBUTES")]
    internal sealed class CloneVariantsAttribute : global::System.Attribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CloneVariantsAttribute"/> class.
        /// </summary>
        /// <param name="original">The word naming the variant the method is written for, such as <c>Bmp</c>.</param>
        /// <param name="variants">The words naming the variants to write, such as <c>Gif</c> and <c>Png</c>.</param>
        public CloneVariantsAttribute(string original, params string[] variants)
        {
        }
    }
}
""";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx => ctx.AddSource(
            "CloneVariantsAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var variants = CloneTarget.ForAttribute(context.SyntaxProvider, AttributeName)
            .SelectMany(static (target, ct) => Clone(target, ct))
            .WithTrackingName("Clone");

        ClonedMethodOutput.Register(context, variants, VariantDiagnostics.CollidingVariants);
    }

    private static ImmutableArray<ClonedMethod> Clone(CloneTarget target, CancellationToken ct)
    {
        var context = target.Context;
        var syntax = target.Syntax;
        var isTargetType = context.TargetSymbol is ITypeSymbol;

        var symbol = isTargetType
            ? context.SemanticModel.GetDeclaredSymbol(syntax, ct)
            : context.TargetSymbol as IMethodSymbol;

        if (symbol is null
            || context.Attributes[0].ConstructorArguments is not [{ Value: string original }, { Values: var variants }]
            || !MethodLocation.TryCreate(syntax, symbol, out var location, out var root))
        {
            return ImmutableArray<ClonedMethod>.Empty;
        }

        // An attribute on the method wins over the one on its type.
        if (isTargetType && symbol.GetAttributes().Any(static a => a.AttributeClass?.ToDisplayString() == AttributeName))
        {
            return ImmutableArray<ClonedMethod>.Empty;
        }

        // Each variant keeps the nullable context the method was written in, so that a method
        // written without annotations does not gain them in its variants.
        var disableNullable = !context.SemanticModel.GetNullableContext(syntax.SpanStart).AnnotationsEnabled();

        var name = syntax.Identifier.ValueText;

        if (name.IndexOf(original, StringComparison.Ordinal) < 0)
        {
            var diagnostic = ReportedDiagnostic.Create(VariantDiagnostics.NameWithoutOriginal, syntax.Identifier.GetLocation(), name);
            return ImmutableArray.Create(ClonedMethod.Create(location, syntax, syntax, disableNullable, ImmutableArray.Create(diagnostic)));
        }

        var clones = ImmutableArray.CreateBuilder<ClonedMethod>();

        foreach (var variant in variants)
        {
            if (variant.Value is not string to || string.Equals(to, original, StringComparison.Ordinal))
            {
                continue;
            }

            var rewriter = new VariantRewriter(context.SemanticModel, syntax, original, to);
            var rewritten = rewriter.Visit(root);

            // Every variant is a copy of the same method, so each file is named after the variant
            // rather than after the original, which would give all of them the same file.
            clones.Add(ClonedMethod.Create(location, syntax, rewritten, disableNullable, rewriter.Diagnostics, VariantRewriter.Rename(name, original, to)));
        }

        return clones.ToImmutable();
    }
}
